@extends('frontend.master')
    @section('content')
    <section class="ps-inner-page">

        <div class ="container" style = "justify-content:center">
            <br/>
                                    <h5 class="text-uppercase m-b-5" style = "font-size:30px">Terms &amp; Conditions</h5>
                                    <div class="">
                                            <div class="thumbnail thumbnail--no-border">
                                                <div class="caption">
                                                    <p>Welcome to our website. If you continue to access and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern Online Aushadhi's relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website. You must be 18 years of age or older to register or use the website in any manner. By registering, using  the website or accepting this agreement, you represent and warrant to Online Aushadhi that you are 18 years of age or older, and that you have the right, authority and capacity to use the website and agree to and abide by this agreement.</p>
                                                    <p>All products and services of Online Aushadhi are subject to the terms and conditions of the applicable agreements governing their use or sale. These terms are to be read by you together with any terms, conditions or disclaimers provided in the pages of the site. The information, material and content provided in the site may be changed at any time without notice. Changes may be made to these terms and conditions including the privacy policies at any time without notice by updating this posting. You agree to review these terms regularly and your continued access or use of the site will mean that you agree to any changes. </p>
                                                    <p>The term 'Online Aushadhi' or 'us' or 'we' refers to the owner of the website. The term 'you' refers to the user or viewer of our website.</p>
                                                    <p>The use of this website is subject to the following terms of use:</p><br/>
                                                    <ul class="list-unstyled main-terms more-gutter">
                                                        <li><span class="title title--sm">Informational Purpose</span>
                                                            <p>The content of the pages of this website is for informational purpose only and is not intended to provide specific advice for you, and should not be relied upon in that regard. You should not act or rely on the information without seeking the advice of a professional. You should not use the information contained on this site for diagnosing, treating, curing or preventing a health problem or prescribing a medication. Always consult your own physician for advice and treatment. You should carefully read all information provided by the manufacturers of the product on or in the product packaging and labels before using it. </p>
                                                        </li><br/>
                                                        <li><span class="title title--sm">Disclaimer</span>
                                                            <p>The information contained in this website is for general information purposes only. The information is provided by Online Aushadhi and while we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. Further, we do not represent or warrant that the site will be available or meet your requirements, that access will be uninterrupted, that there will be no delays, failures, errors or omissions or loss of transmitted information, that no viruses or other contaminating or destructive properties will be transmitted, or that no damage will occur to your computer system. Every effort is made to keep the website up and running smoothly. However, Online Aushadhi takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control. You have sole responsibility for adequate protection and backup of data and/or equipment and to take all precautions to scan for computer viruses or other destructive properties.</p>
                                                            <p>Through this website you are able to link to other websites which are not under the control of Online Aushadhi. We have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.</p>
                                                        </li><br/>
                                                        
                                                        <li><span class="title title--sm">Risks and Laws</span>
                                                            <p>Online Aushadhi believes that any Pharmaceuticals ordered were lawfully prescribed to the customer by a medical doctor licensed to practice medicine under a written prescription for the same, a true and complete copy of which (image of prescription) has been provided by the customer to Online Aushadhi with the order. Customer understands that Online Aushadhi will not honor any order for prescription medication unless the customer delivers the copy of prescribing physicians original prescription.</p>
                                                            <p>Online Aushadhi strictly prohibits ordering prescription medicines with fake and unauthorized prescriptions and reviews every prescription carefully before dispensing any products. But if any customer tries to order with such unauthorized prescriptions and are successful (only in rare cases), you do so on your own initiative and are responsible for compliance with applicable local, national or international laws.  In this condition the customer is also solely responsible for any physical, mental or other harm that may occur to anyone due to this unauthorized ordering.</p>
                                                        </li><br/>
                                                        <li><span class="title title--sm">Email</span>
                                                            <p>Any unprotected E-Mail communication over the Internet is, as with communication via any other medium (e.g. cellular phones), not confidential, subject to possible interception or loss, and is also subject to possible alteration. Online Aushadhi is not responsible for and will not be liable to you or anyone else for any damages in connection with an E-Mail sent by you to us or an E-Mail sent by us to you at your request. </p>
                                                        </li><br/>
                                                        <li><span class="title title--sm">Your Transmission</span>
                                                            <p>Any material, information or idea you transmit to or post on this site by any means will be treated as non-proprietary, and may be used by Online Aushadhi for any purpose whatsoever. You are prohibited from posting or transmitting to or from this site any unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, pornographic, or profane material, or any other material that could give rise to any civil or criminal liability under the law. </p>
                                                        </li><br/>
                                                        <li><span class="title title--sm">Severability</span>
                                                            <p>If a portion or part of this terms and conditions is declared invalid, illegal or unenforceable by any court or competent authority then such invalidity or unenforceability of any provisions of this agreement shall not affect the validity or enforceability of any other provision of this agreement, which shall remain in full force and effect.</p>
                                                        </li>
                                                    </ul>
                                                    <div class="regards">
                                                        <p>Yours Faithfully<br><span>Online Aushadhi Team</span></p>
                                                        <p>Last Updated on 12th August, 2015</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                                                    </div>
    </section>
                                    @endsection